### ISSUE TITLE
Error on record alias

### ISSUE THREAD

**Issue by caiohasouza** [terraform-aws-modules/terraform-aws-route53#9]
I'm using the example provided and when the alias is configured i have this error:

> Error: Inconsistent conditional result types
> 
>   on .terraform/modules/records/terraform-aws-route53-1.0.0/modules/records/main.tf line 15, in resource "aws_route53_record" "this":
>   15:   for_each = var.create && (var.zone_id != null || var.zone_name != null) ? local.recordsets : {}
>     |----------------
>     | local.recordsets is object with 2 attributes
>     | var.create is true
>     | var.zone_id is null
>     | var.zone_name is "myapp.com"
> 
> The true and false result expressions must have consistent types. The given
> expressions are object and object, respectively.

OBS: Terraform v0.12.28

Could you help me please?

**Comment by rodrigondec** [comment]
Bumped on the same error.

Some follow up @caiohasouza ?

**Comment by staticaland** [comment]
I think it has something to do with mixing alias records with regular records?

**Comment by antonbabenko** [comment]
Thanks for opening this issue. I have just fixed it in #11 where I also added examples for S3 bucket and CloudFront distribution.

Please give a try for [v1.2.0](https://github.com/terraform-aws-modules/terraform-aws-route53/releases/v1.2.0) which has been just released.

**Comment by amozgovoy** [comment]
with `v1.2.0`, terraform `v0.12.29` and the following code:
```
module "dns_records" {
  source  = "terraform-aws-modules/route53/aws//modules/records"
  create = var.environment == "production" ? true : false
  version = "~> 1.0"
  zone_id = var.dns_settings.zone_id
  ...
  ...
```
when create is `false` (`var.environment` is not `production`):
```
Error: Call to unknown function

  on .terraform/modules/acme.dns_records/modules/records/main.tf line 15, in resource "aws_route53_record" "this":
  15:   for_each = var.create && (var.zone_id != null || var.zone_name != null) ? local.recordsets : object({})

There is no function named "object".
```

**Comment by amozgovoy** [comment]
It could be a different issue just introduced with the fix #11 you mentioned above

**Comment by amozgovoy** [comment]
nevermind, it is fixed already by #14

**Comment by savon-noir** [comment]
Hello,

fyi, the issue is popping up with terraform version < 0.13.0.

I was running terraform v0.12.29 and terragrunt version v0.23.28 on a records set containing record alias. When these conditions are met, following error still occurs:
```
Error: Inconsistent conditional result types

  on main.tf line 15, in resource "aws_route53_record" "this":
  15:   for_each = var.create && (var.zone_id != null || var.zone_name != null) ? local.recordsets : tomap({})
    |----------------
    | local.recordsets is object with 4 attributes
    | var.create is true
    | var.zone_id is "<REDACTED>"
    | var.zone_name is null

The true and false result expressions must have consistent types. The given
expressions are object and map of dynamic, respectively.
```
upgrading terraform to v0.13.0 fixed the issue. 

I would suggest updating the [requirements table](https://github.com/terraform-aws-modules/terraform-aws-route53#requirements)

It is also interesting to note that, I've also tested using a local copy of the v1.5.0 of the terraform-aws-route53 module and could make it work "properly" with terraform version v0.12.28 and v0.12.29 by replacing tomap({}) by object({}) (same approach as in v1.3.0).
